nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: '${GH_PACKAGES_STUDOCU_TOKEN:-GITHUB_TOKEN}'

npmScopes:
  studocu:
    npmRegistryServer: 'https://npm.pkg.github.com/'

